version: '2'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 10000:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/atm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=luissoy
    networks:
      - springboot-mysql-network

  mysqldb:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=atm
      - MYSQL_ROOT_PASSWORD=luissoy
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

networks:
  springboot-mysql-network:
    name: springboot-mysql-network